services:
    enersee_laravel_backend:
        build:
            args:
                user: ShakilAhmmed
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        platform: linux/amd64
        image: enersee-laravel-backend
        container_name: enersee-laravel-backend-application
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage/app/public/temp:/tmp
            - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
        env_file:
            - ./.env
        depends_on:
            - enersee_laravel_database
        links:
            - enersee_laravel_database
        networks:
            - enersee-laravel-network
    enersee_laravel_nginx:
        image: nginx:alpine
        container_name: enersee-laravel-nginx
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - enersee-laravel-network
        depends_on:
            - enersee_laravel_database
            - enersee_laravel_phpmyadmin
    enersee_laravel_database:
        image: mysql:8.0.2
        container_name: enersee-laravel-database
        restart: unless-stopped
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - enersee-laravel-network
    enersee_laravel_phpmyadmin:
        image: phpmyadmin
        container_name: enersee-laravel-phpmyadmin
        restart: always
        tty: true
        depends_on:
            - enersee_laravel_database
        ports:
            - "${PMA_PORT}:80"
        environment:
            PMA_HOST: enersee_laravel_database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 2048M
        networks:
            - enersee-laravel-network
networks:
    enersee-laravel-network:
        driver: bridge
