"""Meters and Consmption Table

Revision ID: 27dd8cc3e378
Revises: 0b6e506693e9
Create Date: 2025-10-02 12:44:02.964684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27dd8cc3e378'
down_revision: Union[str, None] = '0b6e506693e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consumptions_id', table_name='consumptions')
    op.drop_table('consumptions')
    op.drop_table('meters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('unit_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('submeter', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('buildings_site', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('end_client_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('external_meter_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('main_building_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sampling_period', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sampling_period_type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('official_meter', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_consumption', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('utility_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_virtual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('meter_add', mysql.JSON(), nullable=True),
    sa.Column('meter_sub', mysql.JSON(), nullable=True),
    sa.Column('building_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('consumptions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('energy_use', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name='consumptions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_consumptions_id', 'consumptions', ['id'], unique=False)
    # ### end Alembic commands ###
